### ISSUE TITLE
Would be a shame if someone were to...

### ISSUE THREAD

**Issue by samvdkris** [q3w3e3/RustMD5#2]
![IMG_20210204_001138.jpg](https://user-images.githubusercontent.com/22723225/106821514-96b01780-667d-11eb-9c7b-688008f3e2c9.jpg)

**Comment by samvdkris** [comment]
On a more serious note: you might want to take a look at [rayon](https://docs.rs/rayon/) for the multithreading, it's really neat!

**Comment by q3w3e3** [comment]
> On a more serious note: you might want to take a look at [rayon](https://docs.rs/rayon/) for the multithreading, it's really neat! Would also make it easier to divide stuff over multiple threads without unnecessary repeating hashes.

oh hell yeah, that does look good! thanks!
